# Doing some challenges to verify workflow status

name: Beginner Challenge - local substrate development chain

# Controls when the action will run

on:
  push

jobs: 

 main:
    runs-on: ubuntu-latest
    env: 
      current: 'date(%yyyy-%MM-%dd)'
    
    steps:

      - uses: actions/checkout@v2

      - name: install base dev env
        run: |
          sudo apt update
          rustup update nightly
          rustup update stable
          rustup target add wasm32-unknown-unknown --toolchain nightly
          git clone https://github.com/substrate-developer-hub/substrate-front-end-template.git
          cd ./substrate-front-end-template
          yarn install
          yarn start




         



