# Doing some challenges to verify workflow status

name: Beginner Challenge - local substrate development chain

# Controls when the action will run

on:
  push

jobs: 

 main:
    runs-on: ubuntu-latest
    env: 
      current: 'date(%yyyy-%MM-%dd)'
    
    steps:

      - uses: actions/checkout@v2

      - name: install base dev env
        run: |
          sudo apt update
          git clone -b v2.0.0 --depth 1 https://github.com/substrate-developer-hub/substrate-node-template
          rustup update nightly
          rustup update stable
          rustup target add wasm32-unknown-unknown --toolchain nightly
          cd substrate-node-template/
          cargo build --release




         



