# Doing some challenges to verify workflow status

name: Beginner Challenge - local substrate development chain

# Controls when the action will run

on:
  push

jobs: 

 main:
    runs-on: ubuntu-latest
    env: 
      current: 'date(%yyyy-%MM-%dd)'
    
    steps:

      - uses: actions/checkout@v2

      - name: install base dev env
        run: |
#         sudo apt update
         host https://getsubstrate.io
         nslookup https://getsubstrate.io
 #        curl -IL https://getsubstrate.io -sSf | bash -s -- --fast
 #        source ~/.cargo/env 
 #        rustup default stable -y
 #        rustup install nightly-${env.current} -y
 #        rustup target add wasm32-unknown-unknown --toolchain nightly-${env.current}
 #        cargo +nightly-${env.current} ...
 #        rustup update
 #        rustup update nightly
 #        rustup target add wasm32-unknown-unknown --toolchain nightly




         



